//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Books.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InputPrompt {
            get {
                return ResourceManager.GetString("InputPrompt", resourceCulture);
            }
        }
        
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        internal static string BookList {
            get {
                return ResourceManager.GetString("BookList", resourceCulture);
            }
        }
        
        internal static string CountBooksAdded {
            get {
                return ResourceManager.GetString("CountBooksAdded", resourceCulture);
            }
        }
        
        internal static string NotParsedDate {
            get {
                return ResourceManager.GetString("NotParsedDate", resourceCulture);
            }
        }
        
        internal static string DuplicatedBooks {
            get {
                return ResourceManager.GetString("DuplicatedBooks", resourceCulture);
            }
        }
        
        internal static string AddedBooks {
            get {
                return ResourceManager.GetString("AddedBooks", resourceCulture);
            }
        }
        
        internal static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        internal static string OutputMethods {
            get {
                return ResourceManager.GetString("OutputMethods", resourceCulture);
            }
        }
        
        internal static string WrongChoice {
            get {
                return ResourceManager.GetString("WrongChoice", resourceCulture);
            }
        }
        
        internal static string EmptyChoice {
            get {
                return ResourceManager.GetString("EmptyChoice", resourceCulture);
            }
        }
        
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        internal static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        internal static string FilterPrompt {
            get {
                return ResourceManager.GetString("FilterPrompt", resourceCulture);
            }
        }
    }
}
